# Tips and Tricks

- Spell check functionality in RStudio
- New line for each sentence

## Global chunk options

- figure formats

## Meaningful chunk names

## Useful RStudio Addins

- [wordcount](https://github.com/benmarwick/wordcountaddin): Word counts and readability statistics in R markdown documents
- [citr](https://github.com/crsh/citr): RStudio Addin to Insert Markdown Citations
- [gramr](https://github.com/ropenscilabs/gramr): RStudio Addin, function, & shiny app for the write-good linter
- [remedy](https://github.com/ThinkR-open/remedy): RStudio Addins to Simplify Markdown Writing
- [splitChunk](https://github.com/LudvigOlsen/splitChunk): RStudio addin for splitting R Markdown code chunks

## Author name disambiguation

As per APA style, citations in `papaja` documents will be disambiguated if the bibliography file contains multiple authors with the same family but different given names.
This can be a nuisance if the bibliographic information is not maintained meticulously.
Entries such as `author = {John Doe}` and `author = {J. Doe}` are taken to be different authors and will be disambiguated (i.e. "John Doe (1986)" and "J. Doe (1986)").

Disabling author name disambiguation is possible (although it is somewhat beyond the scope of `papaja`).
The definition of the citation style used in `papaja` is given in a citation style language file (CSL, see [Additional-rendering-options]).
We have created a variant of the widely available APA CSL file without author name disambiguation.
To use this variant insert the following into YAML front matter:

~~~yaml
csl: https://tinyurl.com/apa6-no-disambiguation
~~~

Alternatively, you can download the file and use the location on your hard drive instead of the above URL.
Note that using this style can create the false impression that two works are authored by the same author when really they were not.
For example, `author = {John Doe}` and `author = {Jane Doe}` will be displayed as "Doe (1986a)" and "Doe (1986b)".

If you prefer $\LaTeX$ to generate the bibliographic information, we recommend the following approach to disable author name disambiguation:

~~~yaml
lang              : "en-EN" # Optional, added for clarity

biblio-style      : "apa"
biblatexoptions   : "uniquename=false"
header-includes:
  - \DeclareLanguageMapping{english}{english-apa}

output:
  papaja::apa6_pdf:
    citation_package: biblatex
~~~

Specifying `lang` is optional in this case, because `en-EN` is the default.
`pandoc` converts `en-EN` to `english` and inserts it into the document preamble.
Hence, `english` needs to be mapped to `english-apa`.
Similarly, if you want, say, British english you would have to adapt the above as follows:

~~~yaml
lang              : "en-GB" # Required
header-includes:
  - \DeclareLanguageMapping{british}{british-apa}
~~~

A general drawback to this approach is that `biblatex` does not operate on any text in the YAML front matter.
This can be a problem when, for example, the abstract contains citations.
This problem can be addressed with the [text references](https://bookdown.org/yihui/bookdown/markdown-extensions-by-bookdown.html#text-references) feature in `bookdown`.
Replace the text of the abstract in the YAML front matter by

~~~yaml
abstract: (ref:abstract)
~~~

`(ref:abstract)` is a placeholder for text that you can now define in the body of the R Markdown document (e.g., right after the YAML front matter):

~~~
(ref:abstract)
This is the abstract [@doe1986].
~~~

This text will now be processed and citations will be generated as expected.


## Reproducible software environment

- sessionInfo()
- packrat
- checkpoint
- liftr & docker

## RStudio

1. Document outline


<!-- If you discover an error in a data file, never modify it directly, but instead write code to correct the value. Explain why you made the fix. -->

<!-- Before you finish for the day, make sure you can knit the notebook (if you’re using caching, make sure to clear the caches). That will let you fix any problems while the code is still fresh in your mind. -->


## Splitting an R Markdown document

Some authors may prefer to split long manuscripts into multiple component files for better clarity.
There are two basic strategies to split R Markdown documents that can be combined or used in isolation: sourcing R scripts and splitting the R Markdown document.
If the R Markdown document contains a lot of code, it may be helpful to disincorporate parts of the code, such as reading, merging, restructuring, and relabeling data files.
The R scripts can then be executed at the respective section of the document using `source()`.

Some authors may prefer to split long manuscripts into a master or parent document and multiple children.
The master document, for example, consists of the YAML front matter and includes the children, which are themselves R Markdown documents without a YAML front matter.
To include a child document, insert an empty chunk and provide the path to the R Markdown document in the chunk option `child`.
    
    `r ''````{r child = "introduction.Rmd"}
    ```
    `r ''````{r child = "methods.Rmd"}
    ```
    `r ''````{r child = "results.Rmd"}
    ```
    `r ''````{r child = "discussion.Rmd"}
    ```



## Workflow

- Don't edit raw data
- Don't set a working directory
- Generate graphics from R code
- Don't edit word documents
- Relative paths


## Adjusting line spacing

According to the APA guidelines, "Tables may be submitted either single- or double-spaced." [p. 141; @american_psychological_association_publication_2010].
Adjusting the line spacing of table contents is currently not supported in `papaja`.
However, as usual it is possible to adjust the spacing in PDF documents by including additional $\LaTeX$ code.
If you use `apa_able()`, including the following in the YAML front matter will result in single-spaced tables with double-spaced caption and table note:

```{yaml}
header-includes:
  - \usepackage{setspace}
  - \AtBeginEnvironment{tabular}{\singlespacing}
  - \AtBeginEnvironment{lltable}{\singlespacing}
  - \AtBeginEnvironment{tablenotes}{\doublespacing}
  - \captionsetup[table]{font={stretch=1.5}}
  - \captionsetup[figure]{font={stretch=1.5}}
```

Similarly, the line spacing of figure captions can be adjusted as follows:

```{yaml}
header-includes:
  - \usepackage{setspace}
  - \AtBeginEnvironment{tabular}{\doublespacing}
  - \AtBeginEnvironment{lltable}{\doublespacing}
  - \AtBeginEnvironment{tablenotes}{\doublespacing}
  - \captionsetup[table]{font={stretch=1.5}}
  - \captionsetup[figure]{font={stretch=1}}
```


## Troubleshooting

### R

<!-- Copy and paste from R4DS -->
<!-- Troubleshooting R Markdown documents can be challenging because you are no longer in an interactive R environment, and you will need to learn some new tricks. The first thing you should always try is to recreate the problem in an interactive session. Restart R, then “Run all chunks” (either from Code menu, under Run region), or with the keyboard shortcut Ctrl + Alt + R. If you’re lucky, that will recreate the problem, and you can figure out what’s going on interactively. -->

<!-- If that doesn’t help, there must be something different between your interactive environment and the R markdown environment. You’re going to need to systematically explore the options. The most common difference is the working directory: the working directory of an R Markdown is the directory in which it lives. Check the working directory is what you expect by including getwd() in a chunk. -->

<!-- Next, brainstorm all the things that might cause the bug. You’ll need to systematically check that they’re the same in your R session and your R markdown session. The easiest way to do that is to set error = TRUE on the chunk causing the problem, then use print() and str() to check that settings are as you expect. -->


