# Limitations

As outlined in [Document compilation], `papaja` builds on `pandoc` to render Markdown into PDF and DOCX documents.
Markdown provides good common basis for these and other document types but the common basis necessarily limits the degree of control that can be exerted over the rendered document.
For example, there is currently no way to generate tables with `pandoc` in which cells span multiple rows or columns.
Similarly, it is not possible to insert page breaks into a document.
Both of these limitations have been raised with the developers of `pandoc` (see [here](https://github.com/jgm/pandoc/issues/1024) and [here](https://github.com/jgm/pandoc/issues/1934)), but it may take a while for them to be addressed.


## PDF documents

`pandoc` builds on LaTeX to render PDF documents.
As discussed in [Markdown text formatting], when the R Markdown document contains LaTeX code it is kept as-is and can be used to exert greater control over the final result.
For example, to create a page break in the rendered document you can use the LaTeX command `\pagebreak`.
Similarly, tables with column spanners can be created by using the corresponding LaTeX code.
Hence, the limited control offered by `pandoc` can be compensated by using LaTeX code and `papaja` resorts to this approach, for example, in `apa_table()`.


## Microsoft Word documents

In contrast, there is no simple way to compensate for the limited control offered by `pandoc` when rendering Microsoft Word documents.
This is the reason why some of `papaja`'s features are only available if the to-be-rendered document is in PDF format, such as some [Rendering options] and some features of `apa_table()` (see [Tables]).
More over, rendered documents in DOCX format require some manual work before they fully comply with APA guidelines.
We, therefore, provide the following checklist of necessary changes:

1. add a running head and page number to the header line
2. add horizontal rules above the column titles and below the last table row
3. position the beginning of the reference section at the top of a new page
4. format the references to have hanging indentation (i.e. indentation of all lines but the first one)
5. move figures and tables to the end of the manuscript
5. in figure captions, add a colon following the figure numbers and italize 
6. remove bold formatting of manuscript title at the beginning of the introduction

If necessary,

1. position author note at the bottom of page 1
2. position abstract at the top of page 2
3. position the beginning of the main text (including the title) at the top of page 3
4. add a colon at the end of level 3-headings
5. add midrules to tables

We hope to automated some of these points in the future as the flexibility of `pandoc` increases.
